#!/bin/sh /etc/rc.common

START=95
STOP=01

USE_PROCD=1

start_service() {
    config_load rtp2httpd
    config_get fcc_nat_traversal "$1" fcc_nat_traversal '0'
    config_get port "$1" port '8080'

    procd_open_instance
    procd_set_param command /usr/bin/rtp2httpd -n $fcc_nat_traversal -q -l $port
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}