#!/bin/sh /etc/rc.common

START=95
STOP=01

USE_PROCD=1

start_service() {
    config_load rtp2httpd
    config_get verbosity global verbosity '2'
    config_get fcc_nat_traversal global fcc_nat_traversal '0'
    config_get bind_address global bind_address '*'
    config_get bind_port global bind_port '8080'

    procd_open_instance
    procd_set_param command /usr/bin/rtp2httpd -v $verbosity -c /etc/rtp2httpd/rtp2httpd.conf -f $fcc_nat_traversal
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}